index_podcast/index_podcast/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView, PoliticsView, IntroPage, SettingsView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', IndexView.as_view(), name='index'),
    path('intro/', IntroPage.as_view(), name='intro'),
    path('privacy_policy/', PoliticsView.as_view(), name='privacy_policy'),
    path('mypodcasts/', include('mypodcasts.urls')),
    path('', include('publish_podcasts.urls')),
    path('settings/', include('category.urls')),
    path('settings/', include('languages.urls')),
    path('settings/', SettingsView.as_view(), name='settings'),
    path('stats/', include('stats.urls')),
    path('reports/', include('reports.urls')),
]

index_podcast/publish_podcasts/urls.py
from django.urls import path, include
from .views import PodcastDetailView, PodcastRSSView

app_name = 'publish_podcast'

urlpatterns = [
    path('podcasts/user_<int:user_id>/<int:pk>/', PodcastDetailView.as_view(), name="podcast-detail"),
    path('podcasts/user_<int:user_id>/<int:pk>/rss/', PodcastRSSView.as_view(), name="podcast-rss"),
]

index_podcast/stats/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .api_views import ViewsPodcastViewSet, ViewsEpisodeViewSet, StatsPodcastViewSet
from .views import StatsView

app_name = 'stats'

router = DefaultRouter()
router.register(r'podcast', ViewsPodcastViewSet, basename='views-podcast')
router.register(r'episode', ViewsEpisodeViewSet, basename='views-episode')
router.register(r'statistics', StatsPodcastViewSet, basename='statistics')

urlpatterns = [
    path('api/', include(router.urls)),
    path('', StatsView.as_view(), name='stats'),
]

index_podcast/publish_podcasts/views.py
from django.views.generic import DetailView
from mypodcasts.models import Podcast, Episode
from stats.models import ViewsPodcast


class PodcastDetailView(DetailView):
    model = Podcast
    template_name = 'publish_podcasts/podcast-1.html'

    def get_queryset(self):
        return Podcast.objects.filter(owner=self.kwargs['user_id'])

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        ViewsPodcast(podcast=obj).save()
        return obj


class PodcastRSSView(DetailView):
    model = Podcast
    template_name = 'publish_podcasts/feed.rss'

    def get_queryset(self):
        return Podcast.objects.filter(owner=self.kwargs['user_id'])

index_podcast/templates/publish_podcasts/podcast-1.html
{% load static %}
{% get_media_prefix as MEDIA_PREFIX %}
{% load extra_filters %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script>
        const CRSF_TOKEN = "{{ csrf_token }}";
    </script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143546509-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());
        gtag('config', 'UA-143546509-1');
    </script>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>{{ object.title }}</title>
    <link type="application/rss+xml" rel="alternate" title="{{ object.title }}"
          href="https://{{ request.get_host }}{% url 'publish_podcast:podcast-rss' object.owner.id object.id %}"/>
    <link rel="stylesheet" href="{% static 'style/null.css' %}">
    <link rel="stylesheet" href="{% static 'style/podcast.css' %}">
    <link rel="stylesheet" href="{% static 'style/media-podcast.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap"
          rel="stylesheet">
    <style>
        .filter-label {
            font-size: 20px;
            color: #2aabd2;
        }

        .filter-input {
            font-size: 20px;
        }
    </style>
</head>
<body>
<div class="blur-block-header">
    <div class="blur-blur"></div>
    <div class="blur-transparency white"></div>
    <div class="blur-conteiner podcast_header">
        <div class="podcast_block">
            <div class="podcast_block_img">
                <img class="podcast_block_img-img" src="{{ MEDIA_PREFIX }}{{ object.image }}" alt="">
                <div class="feed-block-leaving">
                    <div class="feed-block-leaving-menu">
                    </div>
                    <div class="feed-block-leaving-menu-item-group">
                        <a href="https://www.youtube.com/channel/{{ object.owner.channelid }}" target="_blank"
                           class="feed-block-leaving-menu-item youtube-logo"></a>
                        {% if object.link_apple %}
                            <a href="{{ object.link_apple }}" target="_blank"
                               class="feed-block-leaving-menu-item apple-logo">
                            </a>
                        {% endif %}
                        {% if object.link_google %}
                            <a href="{{ object.link_google }}" target="_blank"
                               class="feed-block-leaving-menu-item google-logo">
                            </a>
                        {% endif %}
                        {% if object.link_spotify %}
                            <a href="{{ object.link_spotify }}" target="_blank"
                               class="feed-block-leaving-menu-item spotify-logo">
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="podcast_block_info">
                <div class="podcast_block_authot">
                    {{ object.author }}
                </div>
                <div class="podcast_block_name">
                    {{ object.title }}
                </div>
                <div class="podcast_block_episods">
                    {{ object.episodes.count }}
                </div>
                <!-- добавить описание {{ object.description }} -->
            </div>
        </div>
    </div>
</div>
<div class="blur-block-content">
    <div class="blur-blur blur-blur-content"></div>
    <div class="blur-transparency black"></div>
    <div class="blur-conteiner content" id="content">
        <div>
            <label class="filter-label" for="search-input">Search</label>
            <input class="filter-input" id="search-input" type="text" placeholder="Search request">
        </div>
        <div>
            <label class="filter-label" for="filter-duration">Duration greater than(minutes)</label>
            <input min="0" step="1" placeholder="Min duration" class="filter-input" id="filter-duration" type="number">
        </div>
        <div id="episode-list">
        {% for episode in object.episodes.all|dictsort:"created_date" reversed %}
            <div class="podcast_episode">
                <div class="episode_header">
                    <div class="episode_header_date">
                        {{ episode.created_date }}
                    </div>
                    <div class="episode_header_img_and_btn">
                        <div class="btn-paly icon-play" id="{{ forloop.counter0 }}">
                        </div>
                    </div>
                    <div class="episode_header_time">
                        {{ episode.duration|dur_to_str }}
                    </div>
                </div>
                <div class="episode_content">
                    <div class="episode_content_title">
                        {{ episode.title }}
                        <div class="episode_content_liner"></div>
                    </div>
                    <pre class="episode_content_description description-min">
                        {{ episode.description }}
                        </pre>
                    <input class="episode_content_description_btn" type="button" name="" value="...more">
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
    <div class="window_remove display_none">
        <div class="window_remove_hidden"></div>
        <div class="window_remove_content">
            <div class="window_remove_text">
                Episode is processing...
            </div>
            <div class="window_remove_group_button">
                <div class="window_remove_button_apply" onclick="close_window_alert()">
                    Cancel
                </div>
            </div>
        </div>
    </div>
    <footer>
        <address class="footer-text">
            © 2019 Video2Cast.com
            <nav>
                <a href="{% url 'privacy_policy' %}">Privacy policy</a>
            </nav>
        </address>
    </footer>


    <!-- подключаем все скрипты -->

    <script src="{% static 'scripts/jquery-3.4.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'scripts/main.js' %}"></script>
    <script type="text/javascript">
        const USER_ID = {{ object.owner.id }};
        const PODCAST_ID = {{ object.id }};
        // function drawEpisod(item) {
        //     return `
        //     <div class="episode_header">
        //         <div class="episode_header_date">
        //             сегодня
        //         </div>
        //         <div class="episode_header_img_and_btn">
        //             <img class="episode_header_img"
        //                 src=""
        //                 alt="">
        //         </div>
        //         <div class="episode_header_time">
        //             48 мин
        //         </div>
        //     </div>
        //     <div class="episode_content">
        //         <div class="episode_content_title">
        //             Название эпизода
        //             <div class="episode_content_liner"></div>
        //         </div>
        //         <pre class="episode_content_description description-min">
        //             Какая-то краткая информация Какая-то краткая информация Какая-то краткая информация Какая-то краткая информация Какая-то краткая информация Какая-то краткая информация Какая-то краткая информация Какая-то краткаяКакая-то
        //             краткая информация Какая-то краткая информация Какая-то краткая информация Какая-то краткая информация
        //             информация Какая-то краткая информация Какая-то краткая информация
        //         </pre>
        //
        //         <input class="episode_content_description_btn" type="button" name="" value="...more">
        //     </div>
        //     `;
        // }
        //
        // function play_episod() {
        //     let contain = document.getElementById("content");
        //     for (let i = 0; i < 2; i++) {
        //         contain.innerHTML += `
        //             <div class="podcast_episode">
        //                 ${drawEpisod()}
        //             </div>
        //         `;
        //     }
        //
        // }

        function whaitClick() {

            $('.episode_content_description_btn').on('click', function (event) {
                event.preventDefault();
                btn = $('.episode_content_description_btn');
                index = btn.index(this);
                value = btn[index].value;
                if (value == "meny...") {
                    btn[index].value = `...more`;
                } else {
                    btn[index].value = `meny...`;
                }
                description = $('.episode_content_description')[index];
                $(description).toggleClass('description-min');
                $(description).toggleClass('description-max');
                title = $('.episode_content_title')[index];
                $(title).toggleClass('description-max');
            });
        }

        whaitClick();
    </script>
    <script type="text/javascript" src="{% static 'scripts/publish/podcast.js' %}"></script>
    <script>
        function durationToStr(value) {
            let res = '';
            let minutes = Math.round(value / 60);
            if (minutes >= 60) {
                res += Math.round(minutes / 60) + " h ";
                minutes %= 60;
            }
            res += minutes + ' min';
            return res
        }

        function episodeComponent(episode, index) {
            return `<div class="podcast_episode">
                <div class="episode_header">
                    <div class="episode_header_date">
                        ${(new Date(episode.created_date)).toLocaleString()}
                    </div>
                    <div class="episode_header_img_and_btn">
                        <div class="btn-paly icon-play" id="${index}">
                        </div>
                    </div>
                    <div class="episode_header_time">
                        ${durationToStr(episode.duration)}
                    </div>
                </div>
                <div class="episode_content">
                    <div class="episode_content_title">
                        ${episode.title}
                        <div class="episode_content_liner"></div>
                    </div>
                    <pre class="episode_content_description description-min">
                        ${episode.description}
                        </pre>
                    <input class="episode_content_description_btn" type="button" name="" value="...more">
                </div>
            </div>`;
        }
        
        function searchFilter(text) {
            let request = $("#search-input")[0].value.toLowerCase();
            return text.toLowerCase().includes(request);
        }

        function filterDuration(duration) {
            let request = +$("#filter-duration")[0].value;
            return duration / 60 >= request;
        }

        function reDrawEpisodes() {
            let html = "";
            for (let i = 0; i < episodes.length; ++i){
                if (searchFilter(episodes[i].title) && filterDuration(episodes[i].duration))
                    html += episodeComponent(episodes[i], i);
            }
            $("#episode-list")[0].innerHTML = html;
        }

        $("#search-input").on("input", () => reDrawEpisodes());
        $("#filter-duration").on("input", () => reDrawEpisodes());
    </script>
</body>
</html>

index_podcast/templates/publish_podcasts/podcast.html
{% extends 'main.html' %}
{% load static %}
{% block head %}
    <link type="application/rss+xml" rel="alternate"
      title="{{ object.title }}"
          href="https://{{ request.get_host }}{% url 'publish_podcast:podcast-rss' object.owner.id object.id %}"/>
    <link rel="stylesheet" href="{% static 'style/podcast.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Ramabhadra|Righteous&display=swap" rel="stylesheet">
{% endblock head %}
{% block title %}{{ object.title }}{% endblock title %}
{% block nav %}{% endblock nav %}
{% block header %}{% endblock header %}
{% block content %}
    {% get_media_prefix as MEDIA_PREFIX %}
    <div class="podcast-block">
        <div class="podcast-header">
            <div class="podcast-cover">
                <img class="podcast-cover-img" src="{{ MEDIA_PREFIX }}{{ object.image }}" alt="podcast cover">
            </div>
            <div class="podcast-main-text">
                <div class="podcast-title">
                    {{ object.title }}
                </div>
                <a href="{{ request.scheme }}://{{ request.get_host }}{% url 'publish_podcast:podcast-rss' object.owner.id object.id %}">
                    <div class="rss-btn">
                        <div class="rss-icon"></div>
                        RSS
                    </div>
                </a>
                <div class="podcast-description">
                    {{ object.description }}
                </div>
            </div>
        </div>
        <div class="podcast-content">
            {% for episode in object.episodes.all|dictsort:"created_date" reversed %}
                <div class="podcast-episod">
                    <div class="episod-count">
                        {{ forloop.revcounter }}
                    </div>
                    <div class="episod-play">
                        <div class="btn-paly icon-play" id="{{ forloop.counter0 }}">
                        </div>
                    </div>
                    <div class="episod-text">
                        <div class="episod-title">
                            {{ episode.title }}
                        </div>
                        <div class="episod-description">
                            {{ episode.description }}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}
{% block js %}
    <script type="text/javascript">
        const USER_ID = {{ object.owner.id }};
        const PODCAST_ID = {{ object.id }};
    </script>
    <script type="text/javascript" src="{% static 'scripts/publish/podcast.js' %}"></script>
{% endblock js %}