index_podcast/index_podcast/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView, PoliticsView, IntroPage, SettingsView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', IndexView.as_view(), name='index'),
    path('intro/', IntroPage.as_view(), name='intro'),
    path('privacy_policy/', PoliticsView.as_view(), name='privacy_policy'),
    path('mypodcasts/', include('mypodcasts.urls')),
    path('', include('publish_podcasts.urls')),
    path('settings/', include('category.urls')),
    path('settings/', include('languages.urls')),
    path('settings/', SettingsView.as_view(), name='settings'),
    path('stats/', include('stats.urls')),
    path('reports/', include('reports.urls')),
]

index_podcast/languages/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (LanguageCreateView, LanguageListView, LanguageDeleteView, LanguageUpdateView)
from .api_views import LanguageViewSet

app_name = 'languages'


router = DefaultRouter()
router.register('languages', LanguageViewSet)

urlpatterns = [
    path('languages', LanguageListView.as_view(), name='list'),
    path('languages/create', LanguageCreateView.as_view(), name='add'),
    path('languages/<int:pk>/update', LanguageUpdateView.as_view(), name='update'),
    path('languages/<int:pk>/delete', LanguageDeleteView.as_view(), name='delete'),
    path('api/', include(router.urls)),
]

index_podcast/stats/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .api_views import ViewsPodcastViewSet, ViewsEpisodeViewSet, StatsPodcastViewSet
from .views import StatsView

app_name = 'stats'

router = DefaultRouter()
router.register(r'podcast', ViewsPodcastViewSet, basename='views-podcast')
router.register(r'episode', ViewsEpisodeViewSet, basename='views-episode')
router.register(r'statistics', StatsPodcastViewSet, basename='statistics')

urlpatterns = [
    path('api/', include(router.urls)),
    path('', StatsView.as_view(), name='stats'),
]

index_podcast/languages/models.py
from django.db import models


class Language(models.Model):
    display = models.CharField(max_length=32)
    code = models.CharField(max_length=6, unique=True)

index_podcast/languages/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from .models import Language
from django.urls import reverse_lazy


class LanguageListView(ListView):
    model = Language
    template_name = 'languages/list_language.html'


class LanguageCreateView(CreateView):
    model = Language
    fields = ('display', 'code')
    template_name = 'languages/add_language.html'
    success_url = reverse_lazy('languages:list')


class LanguageUpdateView(UpdateView):
    model = Language
    fields = ('display', 'code')
    template_name = 'languages/update_language.html'
    success_url = reverse_lazy('languages:list')


class LanguageDeleteView(DeleteView):
    model = Language
    fields = ('display', 'code')
    template_name = 'languages/update_language.html'
    success_url = reverse_lazy('languages:list')

index_podcast/templates/languages/add_language.html
{% extends 'category/base.html' %}
{% block inner_content %}
    <h1>Add language</h1>
    <form method="post" style="font-size: 18px">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
{% endblock inner_content %}

index_podcast/templates/languages/list_language.html
{% extends 'category/base.html' %}
{% block inner_content %}
    <h1>languages</h1>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Language</th>
            <th scope="col">Code</th>
        </tr>
        </thead>
        <tbody>
        {% for language in object_list %}
            <tr>
                <td scope="row">{{ language.pk }}</td>
                <td><a href="{% url 'languages:update' language.pk %}">{{ language.display }}</a></td>
                <td>{{ language.code }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock inner_content %}

index_podcast/templates/languages/update_language.html
{% extends 'category/base.html' %}
{% block inner_content %}
    <h1>Update language</h1>
    <form method="post" style="font-size: 18px">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Update">
    </form>
    <form method="post" action="{% url 'languages:delete' object.pk %}">{% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    </form>
{% endblock inner_content %}