index_podcast/index_podcast/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView, PoliticsView, IntroPage, SettingsView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', IndexView.as_view(), name='index'),
    path('intro/', IntroPage.as_view(), name='intro'),
    path('privacy_policy/', PoliticsView.as_view(), name='privacy_policy'),
    path('mypodcasts/', include('mypodcasts.urls')),
    path('', include('publish_podcasts.urls')),
    path('settings/', include('category.urls')),
    path('settings/', include('languages.urls')),
    path('settings/', SettingsView.as_view(), name='settings'),
    path('stats/', include('stats.urls')),
    path('reports/', include('reports.urls')),
]

index_podcast/mypodcasts/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .api_views import api_view_my_videos, PodcastViewSet, EpisodeViewSet
from .views import PodcastListView, AddEpisodeView, EditPodcastView

app_name = 'mypodcasts'

router = DefaultRouter()
router.register(r'podcasts', PodcastViewSet)
router.register(r'episodes', EpisodeViewSet)

urlpatterns = [
    path('api/videos', api_view_my_videos, name='my_videos'),
    path('api/', include(router.urls)),
    path('', PodcastListView.as_view(), name="list-create"),
    path('add-episodes/', AddEpisodeView.as_view(), name='episodes-add'),
    path('<int:pk>/', EditPodcastView.as_view(), name='podcast-edit'),
]

index_podcast/reports/urls.py
from django.urls import path
from .views import PodcastHTMLView, EpisodesView, EpisodesPDF, PodcastsPdf

app_name = 'reports'

urlpatterns = [
    path('podcasts/html', PodcastHTMLView.as_view(), name='podcasts-html'),
    path('episodes/html', EpisodesView.as_view(), name='episodes-html'),
    path('podcasts/pdf', PodcastsPdf.as_view(), name='podcasts-pdf'),
    path('episodes/pdf', EpisodesPDF.as_view(), name='episodes-pdf'),
]

index_podcast/stats/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .api_views import ViewsPodcastViewSet, ViewsEpisodeViewSet, StatsPodcastViewSet
from .views import StatsView

app_name = 'stats'

router = DefaultRouter()
router.register(r'podcast', ViewsPodcastViewSet, basename='views-podcast')
router.register(r'episode', ViewsEpisodeViewSet, basename='views-episode')
router.register(r'statistics', StatsPodcastViewSet, basename='statistics')

urlpatterns = [
    path('api/', include(router.urls)),
    path('', StatsView.as_view(), name='stats'),
]

index_podcast/templates/main.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143546509-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());
        gtag('config', 'UA-143546509-1');
    </script>
    <title>{% block title %}Video2Cast{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'style/null.css' %}">
    <link rel="stylesheet" href="{% static 'style/main.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Ramabhadra|Righteous&display=swap" rel="stylesheet">
    <script>
        const CRSF_TOKEN = "{{ csrf_token }}";
    </script>
    {% block head %}
    {% endblock head %}
    ﻿
</head>
﻿
<body>
<div class="blur-block header">
    {% block header %}
        <div class="blur-blur"></div>
        <div class="blur-transparency black"></div>
    {% endblock header %}
    {% block nav %}
        <div class="blur-conteiner nav">
            <menu>
                <li>
                    <a href="{% url 'index' %}">
                        <div class="nav-button">
                            <div class="nav-button-icon"></div>
                            <div class="nav-button-text">
                                Home
                            </div>
                        </div>
                    </a>
                    <a href="{% url 'mypodcasts:list-create' %}">
                        <div class="nav-button">
                            <div class="nav-button-icon"></div>
                            <div class="nav-button-text">
                                My Podcasts
                            </div>
                        </div>
                    </a>
                    <a href="{% url 'mypodcasts:episodes-add' %}">
                        <div class="nav-button">
                            <div class="nav-button-icon"></div>
                            <div class="nav-button-text">
                                Add Episodes
                            </div>
                        </div>
                    </a>
                    <a href="{% url 'settings' %}">
                        <div class="nav-button">
                            <div class="nav-button-icon"></div>
                            <div class="nav-button-text">
                                Settings
                            </div>
                        </div>
                    </a>
                    <a href="{% url 'stats:stats' %}">
                        <div class="nav-button">
                            <div class="nav-button-icon"></div>
                            <div class="nav-button-text">
                                Statistics
                            </div>
                        </div>
                    </a>
                    <a href="{% url 'reports:podcasts-pdf' %}">
                        <div class="nav-button">
                            <div class="nav-button-icon"></div>
                            <div class="nav-button-text">
                                Report of podcasts
                            </div>
                        </div>
                    </a>
                    <a href="{% url 'reports:episodes-pdf' %}">
                        <div class="nav-button">
                            <div class="nav-button-icon"></div>
                            <div class="nav-button-text">
                                Report of podcasts
                            </div>
                        </div>
                    </a>
                </li>
                <li>
                    {% if user.is_authenticated %}
                        <form method="POST" action="{% url 'account_logout' %}">
                            {% csrf_token %}
                            <div class="nav-button nav-button-bottm">
                                <div class="nav-button-icon"></div>
                                <button type="submit" class="nav-button-text"
                                        style="background: none;border: none;color: white">
                                    Log out
                                </button>
                            </div>
                        </form>
                    {% else %}
                        <a href="{% provider_login_url "google" next="/" %}">
                            <div class="nav-button nav-button-bottm">
                                <div class="nav-button-icon"></div>
                                <div class="nav-button-text">Login</div>
                            </div>
                        </a>
                    {% endif %}
                </li>
            </menu>
        </div>
    {% endblock nav %}
</div>
<main>
    <div class="logo-name blur-block box-shadow">
        <div class="blur-blur"></div>
        <div class="blur-transparency-logo white"></div>
        <div class="blur-conteiner p-15">
            <a href="{% url 'index' %}">VIDEO2CAST</a>
        </div>
    </div>

    <div class="content box-shadow" id="content">
        {% block content %}

        {% endblock content %}
    </div>

    <footer>
        <address class="footer-text">
            © 2019 Video2Cast.com
            <nav>
                <a href="{% url 'privacy_policy' %}">Privacy policy</a>
            </nav>
        </address>
    </footer>
</main>
<script src="{% static 'scripts/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'scripts/main.js' %}"></script>
{% block js %}
{% endblock js %}
</body>
﻿
</html>

index_podcast/templates/privacy_policy.html
{% extends 'main.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'style/privacy_policy.css' %}">
{% endblock head %}
{% block title %}Privacy policy{% endblock title %}
{% block content %}
<h1>Privacy policy</h1>
<div class="privacy-block">
    <h2 class="privacy-titel">1. INFORMATION COLLECTED BY US</h2>
    <div class="liner-b"></div>
    <div class="privacy-text">
        <h3>We collect the following information.</h3>
        <h3>Information you provide us directly:</h3>
        <ul>
            <li>
                <p>Your email the address entered when logging
                    into your YouTube account via Video2Cast.</p>
            </li>
            <li>
                <p>Correspondence between you and Video2Cast.
                    For example, we can send you an emails related
                    to the Service (such as registration confirmation,
                    information about changes and updates to the
                    functions of the Service, technical notices and
                    safety notices). Please note that you can not
                    refuse to receive emails associated with the
                    Service.</p>
            </li>
        </ul>
        <h3>Analytical information:</h3>
        <ul>
            <li>
                <p>We use third-party analysis tools to assess
                    traffic and trends in the use of the Service.
                    These tools collect information sent by your
                    device or our Service, including data on the
                    pages you visited, browser extensions, and other
                    information that can help us improve the Service.
                    We collect and use this analytical information
                    in conjunction with the analytical information
                    obtained from other Users, in such a way that
                    on its basis it is objectively impossible to
                    determine the identity of a particular User.</p>
            </li>
        </ul>
        <h3>Cookies and similar technologies:</h3>
        <ul>
            <li>
                <p>When you visit the Service, we may use cookies
                    and other similar technologies (for example,
                    web beacons and local storage) to collect
                    information about how you use Video2Cast and
                    provide you with relevant functions.</p>
            </li>
        </ul>
    </div>
</div>
<div class="privacy-block">
    <h2 class="privacy-titel">2. HOW WE USE YOUR INFORMATION</h2>
    <div class="liner-b"></div>
    <div class="privacy-text">
        <p>In addition to some of the specific uses of the
            information described in this Privacy Policy, we
            may use the information obtained in order to:</p>
        <ul>
            <li>provide work, improve, test and monitor the
                effectiveness of the Service;</li>
            <li>track metrics, such as total number of
                visitors, traffic and demographic composition.</li>
        </ul>
    </div>
</div>
<div class="privacy-block">
    <h2 class="privacy-titel">3. TRANSFER OF YOUR INFORMATION</h2>
    <div class="liner-b"></div>
    <div class="privacy-text">
        <p>We do not provide or sell your information to third
            parties.</p>
    </div>
</div>
<div class="privacy-block">
    <h2 class="privacy-titel">4. YOUR “YouTube” ACCOUNT INFORMATION</h2>
    <div class="liner-b"></div>
    <div class="privacy-text">
        <p>Our service takes public information about your channel,
            as well as information about the video, access to which
            you give, agreeing to the terms of this policy. The service
            has “read-only” access to the channel, service cannot
            make any changes on the channel.</p>
    </div>
</div>
<div class="privacy-block">
    <h2 class="privacy-titel">5. OTHER SITES AND SERVICES</h2>
    <div class="liner-b"></div>
    <div class="privacy-text">
        <p>We are not responsible for the processing of information
            from other sites or services that contain links to
            ours. In addition, you agree that we do not control
            and are not responsible for third parties to whom
            you provide access to your User Content. If you
            use a third-party site or service and give them
            access to your User Content, then you do so at
            your own risk.</p>
    </div>
</div>
<div class="privacy-block">
    <h2 class="privacy-titel">6. HOW TO CONTACT US</h2>
    <div class="liner-b"></div>
    <div class="privacy-text">
        <p>If you have any questions about the Privacy Policy or
            the Service, find in the Help Center the appropriate
            channel of communication with us.</p>
    </div>
</div>
<div class="privacy-block">
    <h2 class="privacy-titel">7. CHANGES TO PRIVACY POLICY</h2>
    <div class="liner-b"></div>
    <div class="privacy-text">
        <p>From time to time it may be necessary to amend this
            Privacy Policy or update it, for example, to reflect
            updates to the Service or the requirements of the
            law. We will notify you before making changes to
            this Privacy Policy and give you the opportunity to
            study the revised policy before continuing to use
            the Service. If you continue to use Video2Cast or
            the Service after making changes to the Privacy
            Policy, it will mean that you agree to such changes.</p>
    </div>
</div>
{% endblock content %}