index_podcast/category/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (CategoryCreateView, SubCategoryCreateView, CategoryListView, CategoryDeleteView, CategoryUpdateView,
                    SubCategoryUpdateView, SubCategoryDeleteView)
from .api_views import CategoryViewSet
app_name = 'category'

router = DefaultRouter()
router.register('category', CategoryViewSet)

urlpatterns = [
    path('category', CategoryListView.as_view(), name='list-category'),
    path('category/create', CategoryCreateView.as_view(), name='add-category'),
    path('category/<int:pk>/update', CategoryUpdateView.as_view(), name='update-category'),
    path('category/<int:pk>/delete', CategoryDeleteView.as_view(), name='delete-category'),
    path('subcategory/create', SubCategoryCreateView.as_view(), name='add-subcategory'),
    path('subcategory/<int:pk>/update', SubCategoryUpdateView.as_view(), name='update-subcategory'),
    path('subcategory/<int:pk>/delete', SubCategoryDeleteView.as_view(), name='delete-subcategory'),
    path('api/', include(router.urls)),
]

index_podcast/index_podcast/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView, PoliticsView, IntroPage, SettingsView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', IndexView.as_view(), name='index'),
    path('intro/', IntroPage.as_view(), name='intro'),
    path('privacy_policy/', PoliticsView.as_view(), name='privacy_policy'),
    path('mypodcasts/', include('mypodcasts.urls')),
    path('', include('publish_podcasts.urls')),
    path('settings/', include('category.urls')),
    path('settings/', include('languages.urls')),
    path('settings/', SettingsView.as_view(), name='settings'),
    path('stats/', include('stats.urls')),
    path('reports/', include('reports.urls')),
]

index_podcast/languages/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (LanguageCreateView, LanguageListView, LanguageDeleteView, LanguageUpdateView)
from .api_views import LanguageViewSet

app_name = 'languages'


router = DefaultRouter()
router.register('languages', LanguageViewSet)

urlpatterns = [
    path('languages', LanguageListView.as_view(), name='list'),
    path('languages/create', LanguageCreateView.as_view(), name='add'),
    path('languages/<int:pk>/update', LanguageUpdateView.as_view(), name='update'),
    path('languages/<int:pk>/delete', LanguageDeleteView.as_view(), name='delete'),
    path('api/', include(router.urls)),
]

index_podcast/stats/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .api_views import ViewsPodcastViewSet, ViewsEpisodeViewSet, StatsPodcastViewSet
from .views import StatsView

app_name = 'stats'

router = DefaultRouter()
router.register(r'podcast', ViewsPodcastViewSet, basename='views-podcast')
router.register(r'episode', ViewsEpisodeViewSet, basename='views-episode')
router.register(r'statistics', StatsPodcastViewSet, basename='statistics')

urlpatterns = [
    path('api/', include(router.urls)),
    path('', StatsView.as_view(), name='stats'),
]

index_podcast/category/models.py
from django.db import models


class Category(models.Model):
    display = models.CharField(max_length=64)
    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.display


class SubCategory(models.Model):
    category = models.ForeignKey(Category, related_name='subcategories', on_delete=models.CASCADE)
    display = models.CharField(max_length=64)
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.display

    class Meta:
        unique_together = ('category', 'name')

index_podcast/category/forms.py
from django.views.generic import CreateView
from .models import Category


class CategoryCreateView(CreateView):
    model = Category
    fields = '__alll__'

index_podcast/category/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from .models import Category, SubCategory
from django.urls import reverse_lazy


class CategoryListView(ListView):
    model = Category
    template_name = 'category/list_category.html'


class CategoryCreateView(CreateView):
    model = Category
    fields = ('name', 'display')
    template_name = 'category/add_category.html'
    success_url = reverse_lazy('category:list-category')


class CategoryUpdateView(UpdateView):
    model = Category
    fields = ('name', 'display')
    template_name = 'category/update_category.html'
    success_url = reverse_lazy('category:list-category')


class CategoryDeleteView(DeleteView):
    model = Category
    fields = ('name', 'display')
    template_name = 'category/update_category.html'
    success_url = reverse_lazy('category:list-category')


class SubCategoryCreateView(CreateView):
    model = SubCategory
    fields = ('category', 'name', 'display')
    template_name = 'category/subcategory/add_subcategory.html'
    success_url = reverse_lazy('category:list-category')


class SubCategoryUpdateView(UpdateView):
    model = SubCategory
    fields = ('category', 'name', 'display')
    template_name = 'category/subcategory/update_subcategory.html'
    success_url = reverse_lazy('category:list-category')


class SubCategoryDeleteView(DeleteView):
    model = SubCategory
    fields = ('category', 'name', 'display')
    template_name = 'category/subcategory/update_subcategory.html'
    success_url = reverse_lazy('category:list-category')

index_podcast/templates/category/add_category.html
{% extends 'category/base.html' %}
{% block inner_content %}
    <h1>Add category</h1>
    <form method="post" style="font-size: 18px">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
{% endblock inner_content %}

index_podcast/templates/category/base.html
{% extends 'main.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'style/bootstrap.min.css' %}"/>
{% endblock %}
{% block content %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'category:list-category' %}">Categories<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'category:add-category' %}">Add category</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'category:add-subcategory' %}">Add subcategory</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'languages:list' %}">Languages</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'languages:add' %}">Add language</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block inner_content %}
    {% endblock inner_content %}
{% endblock content %}

index_podcast/templates/category/list_category.html
{% extends 'category/base.html' %}
{% block inner_content %}
    <h1>Categories</h1>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Category</th>
            <th scope="col">Subcategory</th>
        </tr>
        </thead>
        <tbody>
        {% for category in object_list %}
            <tr>
                <td scope="row">{{ category.pk }}</td>
                <td><a href="{% url 'category:update-category' category.pk %}">{{ category.display }}</a></td>
                <td>
                    {% for subcategory in category.subcategories.all %}
                        <a href="{% url 'category:update-subcategory' subcategory.pk %}">{{ subcategory.display }}</a>
                        {% if not forloop.last %}<hr/>{% endif %}
                    {% empty %}
                        Not one exists
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock inner_content %}

index_podcast/templates/category/update_category.html
{% extends 'category/base.html' %}
{% block inner_content %}
    <h1>Update category</h1>
    <form method="post" style="font-size: 18px">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Update">
    </form>
    <form method="post" action="{% url 'category:delete-category' object.pk %}">{% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    </form>
{% endblock inner_content %}